name: power_saving
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  get: ^4.6.6

  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.69.2
  google_fonts: ^6.3.3
  html: ^0.15.6
  shared_preferences: ^2.5.2
  dropdown_search: ^6.0.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "images/710.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/
